### ISSUE TITLE
SX1262MB1PAS not receiving on RX1 

### ISSUE THREAD

**Issue by snelson-senet** [ARMmbed/mbed-semtech-lora-rf-drivers#37]
Hello,

With latest rf-drivers added to the mbed-os-example-lorawan demo for sx1262 support, 
I observe RX1 downlinks are never received on a SX1262DVK1PAS (NucleoL476RG + sx1262 shield). RX2 downlinks are received.

The radio shield bundled with this devkit is the SX1262MB1PAS. From the datasheet it is "especially designed for ISM frequency band available in Australia and North America at 915/923 MHz (+22dBm; TCXO)".

The end device does receives in both RX windows when configured with a SX1262MB2xAS radio shield.  

I am unfamiliar with the sx1262 driver, but I do see there are differences in receiver setup for oscillator type.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1925

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
