### ISSUE TITLE
Full SX126X support

### ISSUE THREAD

**Issue by thendrickson** [ARMmbed/mbed-semtech-lora-rf-drivers#42]
set_tx_continuous_wave() is empty

There are some TODO comments regarding CAD

Are there plans to finish this driver?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2105

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
