### ISSUE TITLE
Make it possible to use shared SPI module

### ISSUE THREAD

**Issue by danluck** [ARMmbed/mbed-semtech-lora-rf-drivers#43]
I have two devices on one physical SPI bus: SX1272 and LIS3DSH accelerometer.
When I create SX1272_LoRaRadio object it catch SPI and I can't use it with another device.

Now I have to change source code of SX1272_LoRaRadio  to make it possible.

I think it will be very usefull to have two ways to create SX1272_LoRaRadio objects: with current-style with GPIO PinNames (MISO, MOSI, SCLK that used to create SPI module inside class) for backward compatibility and new-style with shared SPI in constructor.

Did you going to add this feature in SX1272_LoRaRadio?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2106

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
