### ISSUE TITLE
SX1262 0% Downlink Packet Success Rate for LoRaWAN Class C   

### ISSUE THREAD

**Issue by snelson-senet** [ARMmbed/mbed-semtech-lora-rf-drivers#44]
Hardware Setup:  NucleoL073RZ + SX1262MB2xAS
LoRaWAN Stack:  mbed native stack

Observations:
- Class A: High(>90%) downlink PSR 
- Class C:  low PSR (<10%)  for class A downlinks and 0% for class C downlinks 
- High class A/C PSR switching radio to SX1276MB1LAS
- High class A/C PSR switching stack to Semtech LoRaMac-node

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2128

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”

**Comment by thendrickson** [comment]
@snelson-senet I found the bug. Will be issuing a pull request soon.

**Comment by snelson-senet** [comment]
@thendrickson That's great news!
